name: Download Artifact
description: Download artifact from S3
inputs:
  source:
    description: 'A file or directory (must end with /) to download'
    required: true
  destination:
    description: 'A file or directory to download to'
    required: false
outputs:
  path:
    description: 'The path of the downloaded file or directory'
    value: ${{ steps.download.outputs.result }}
runs:
  using: composite
  steps:
  - id: download
    uses: actions/github-script@v6
    env:
      INPUTS_SOURCE: ${{ inputs.source }}
      INPUTS_DESTINATION: ${{ inputs.destination }}
    with:
      script: |
        const prefix = process.env.IPDX_S3_BUCKET_PREFIX;

        const source = process.env.INPUTS_SOURCE;
        const destination = process.env.INPUTS_DESTINATION || source;

        const sourceFullPath = `${prefix}/${process.env.GITHUB_REPOSITORY}/${process.env.GITHUB_RUN_ID}/${process.env.GITHUB_RUN_ATTEMPT}/${source}`
        const recursiveOption = source.endsWith('/') ? '--recursive' : '';

        const bucket = process.env.IPDX_S3_BUCKET_NAME;

        await exec.exec(`aws s3 cp s3://${bucket}/${sourceFullPath} ${destination} ${recursiveOption}`)

        return destination
      result-encoding: string
