name: Playground

on:
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash

jobs:
  run:
    name: Run
    runs-on: [self-hosted, linux, x64, kubo]
    steps:
      - run: mkdir website && echo "<html><body>Hello</body></html>" > website/index.html
      - uses: pl-strflt/tf-aws-gh-runner/.github/actions/upload-artifact@kubo
        with:
          source: website
      - uses: pl-strflt/tf-aws-gh-runner/.github/actions/download-artifact@kubo
        with:
          source: website/
          destination: website2
      - run: ls -laR
