name: Playground

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/playground.yml

jobs:
  playground:
    name: Play
    runs-on: ["self-hosted", "linux", "x64", "large"]
    steps:
      - run: echo "Hello, world!"
        shell: bash
