name: Playground

on:
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash

jobs:
  run:
    name: Run
    runs-on: [self-hosted, linux, x64, kubo]
    steps:
      - run: aws --version
      - id: prefix
        run: echo "prefix=$(aws sts get-caller-identity | jq .Arn | grep -oP '(?<=/).+(?=-runner-role/)')" > $GITHUB_OUTPUT
      - run: mkdir website && echo "<html><body>Hello</body></html>" > website/index.html
      - run: aws s3 cp website/index.html s3://tf-aws-gh-runner/${{ steps.prefix.outputs.prefix }}/${{ github.repository }}/${{ github.run_id }}/${{ github.run_attempt }}/index.html --acl public-read
      - run: echo "url=https://tf-aws-gh-runner.s3.amazonaws.com/${{ steps.prefix.outputs.prefix }}/${{ github.repository }}/${{ github.run_id }}/${{ github.run_attempt }}/index.html"
